// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StudioUtil
{
    internal sealed partial class Vsix
    {
        public const string Id = "StudioUtil.781b8e24-c81a-4b9e-bbcb-7b53602f6b10";
        public const string Name = "StudioUtil";
        public const string Description = @"A Visual Studio extension with miscellaneous tools to ease development effort, like fluent file cloning.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Jake Soenneker";
        public const string Tags = "";
    }
}
