// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StudioUtil
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string StudioUtilString = "944e58c7-1767-4692-a75d-858605a5cff6";
        public static Guid StudioUtil = new Guid(StudioUtilString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int grpIdMenuProjectItem = 0x0319;
        public const int menu = 0x0321;
        public const int menuGroup = 0x0322;
        public const int CloneAndReplaceCommand = 0x0323;
        public const int SetVariablesCommand = 0x0324;
        public const int InsertInheritDocCommand = 0x0325;
    }
}